### ISSUE TITLE
Ubuntu image in ARM branch is incompatible with QEMU GICv3

### ISSUE THREAD

**Issue by Hnefi** [parsa-epfl/images#6]
Specifying -machine virt,gic-version=3 in QEMU results in an infinite exception loop when using the ubuntu-arm image (ubuntu 18). This may be a kernel issue

See the following:
https://lists.gnu.org/archive/html/qemu-devel/2016-06/msg04148.html

**Comment by liuhubing** [comment]
Hello, have you solved this problem?

**Comment by Hnefi** [comment]
Yes, this has been solved and both the tutorial images, and those in other branches, are functioning.

Closing the issue to reflect this.
